# Generated by Django 4.0.6 on 2022-07-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='root_count',
            new_name='room_count',
        ),
    ]
