# Generated by Django 4.0.6 on 2022-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hotel_amenities_alter_hotelbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimages',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
